import Head from "next/head";
import BlogGrid from "../components/page/blog/BlogGrid";
import BlogIntro from "../components/page/blog/BlogIntro";

export default function blog() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <BlogIntro />
        <BlogGrid />
      </div>
    </div>
  );
}
