import Head from "next/head";

import Intro from "../components/page/home/Intro";
import DashboardView from "../components/page/home/DashboardView";
import Setup from "../components/page/home/Setup";
import News from "../components/page/home/News";
import Plans from "../components/page/home/Plans";
import Shopify from "../components/page/home/Shopify";
import Subscribe from "../components/page/home/Subscribe";
import Partners from "../components/page/home/Partners";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Intro />
        <DashboardView />
        <Partners />
        <Setup />
        <News />
        <Plans />
        <Shopify />
        <Subscribe />
      </div>
    </div>
  );
}
