import Head from "next/head";
import PartnersBody from "../components/page/partners/PartnersBody";
import PartnersIntro from "../components/page/partners/PartnersIntro";

export default function partners() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <PartnersIntro />
        <PartnersBody />
      </div>
    </div>
  );
}
