import Head from "next/head";
import Legal from "../components/page/legal/Legal";

import { PrivacyPolicy } from "../data/PrivacyPolicy";

export default function privacy() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Legal title={PrivacyPolicy.title} text={PrivacyPolicy.text} />
      </div>
    </div>
  );
}
