import React from "react";
import Head from "next/head";
import SolutionsIntro from "../components/page/solutions/SolutionsIntro";
import SolutionsBody from "../components/page/solutions/SolutionsBody";
import Industries from "../components/page/solutions/Industries";

export default function solutions() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <SolutionsIntro />
        <SolutionsBody />
        <Industries />
      </div>
    </div>
  );
}
