import Head from "next/head";

import { TermsConditions } from "../data/TermsConditions";
import Legal from "../components/page/legal/Legal";

export default function terms() {
  return (
    <div>
      <Head>
        <title>Momentum App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Legal title={TermsConditions.title} text={TermsConditions.text} />
      </div>
    </div>
  );
}
